version: '3'

services:
  db:
    image: postgres:latest
    container_name: pgdbDjangoDocker
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "python3 manage.py migrate && python3 manage.py makemigrations && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/srv
    ports:
      - "8000:8000"
    depends_on:
      - db